# Generated by Django 6.0 on 2025-12-29 04:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=50, unique=True, verbose_name='属性タイプ')),
                ('display_name', models.CharField(max_length=100, verbose_name='表示名')),
                ('max_total_limit', models.PositiveIntegerField(help_text='1回の予約で購入できる最大チケット数', validators=[django.core.validators.MinValueValidator(1)], verbose_name='購入上限（1予約あたり）')),
                ('form_schema', models.JSONField(blank=True, default=list, help_text='動的フォームの定義 (JSON形式)', verbose_name='フォームスキーマ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '属性設定',
                'verbose_name_plural': '属性設定',
                'db_table': 'api_attributeconfig',
                'ordering': ['sort_order', 'target_type'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='メールアドレスまたは識別子', max_length=255, verbose_name='ユーザーID')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='代表者名')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('total_tickets', models.PositiveIntegerField(default=0, verbose_name='合計チケット数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='予約日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'db_table': 'api_reservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntrySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField(verbose_name='開催日')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='定員')),
                ('booked_count', models.PositiveIntegerField(default=0, verbose_name='予約済み数')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '入場枠',
                'verbose_name_plural': '入場枠',
                'db_table': 'api_entryslot',
                'ordering': ['event_date', 'start_time'],
                'unique_together': {('event_date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_info', models.JSONField(blank=True, default=dict, help_text='動的フォームの回答 (JSON形式)', verbose_name='ゲスト情報')),
                ('status', models.CharField(choices=[('valid', '有効'), ('entered', '入場済み'), ('cancelled', 'キャンセル')], default='valid', max_length=20, verbose_name='ステータス')),
                ('entered_at', models.DateTimeField(blank=True, null=True, verbose_name='入場日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='api.attributeconfig', verbose_name='属性')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.reservation', verbose_name='予約')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='api.entryslot', verbose_name='入場枠')),
            ],
            options={
                'verbose_name': 'チケット',
                'verbose_name_plural': 'チケット',
                'db_table': 'api_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50, verbose_name='アクション')),
                ('success', models.BooleanField(verbose_name='成功')),
                ('message', models.TextField(blank=True, verbose_name='メッセージ')),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='端末ID')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='操作者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_logs', to='api.ticket', verbose_name='チケット')),
            ],
            options={
                'verbose_name': 'チェックインログ',
                'verbose_name_plural': 'チェックインログ',
                'db_table': 'api_checkinlog',
                'ordering': ['-created_at'],
            },
        ),
    ]
