# Generated by Django 5.2.9 on 2025-12-29 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='attributeconfig',
            name='cancel_deadline_hours',
            field=models.PositiveIntegerField(default=24, help_text='入場時刻の何時間前までキャンセル可能か', verbose_name='キャンセル期限（時間前）'),
        ),
        migrations.AddField(
            model_name='attributeconfig',
            name='is_cancellable',
            field=models.BooleanField(default=True, help_text='ユーザー自身によるキャンセルを許可するか', verbose_name='キャンセル可'),
        ),
        migrations.AddField(
            model_name='attributeconfig',
            name='is_modifiable',
            field=models.BooleanField(default=True, help_text='購入後のゲスト情報修正を許可するか', verbose_name='情報修正可'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_identifier',
            field=models.CharField(blank=True, help_text='非ログインユーザーの識別子（メールアドレス等）', max_length=255, verbose_name='ゲスト識別子'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
