# Generated by Django 5.2.9 on 2025-12-30 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_reservation_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('priority', models.CharField(choices=[('info', 'お知らせ'), ('warning', '注意'), ('critical', '緊急')], default='info', max_length=20, verbose_name='重要度')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('target_slot', models.ForeignKey(blank=True, help_text='特定の入場枠に関するお知らせの場合に選択', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='api.entryslot', verbose_name='対象入場枠')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
                'db_table': 'api_announcement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_token', models.CharField(max_length=64, unique=True, verbose_name='譲渡トークン')),
                ('status', models.CharField(choices=[('pending', '未受取'), ('accepted', '受取済み'), ('expired', '期限切れ'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='受取日時')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL, verbose_name='送信者')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='api.ticket', verbose_name='チケット')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL, verbose_name='受取者')),
            ],
            options={
                'verbose_name': 'チケット譲渡',
                'verbose_name_plural': 'チケット譲渡',
                'db_table': 'api_tickettransfer',
                'ordering': ['-created_at'],
            },
        ),
    ]
