# Generated by Django 5.2.9 on 2025-12-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_announcement_tickettransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='コード')),
                ('discount_amount', models.IntegerField(help_text='円単位', verbose_name='割引額')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='有効開始日時')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='有効終了日時')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='使用回数上限')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='使用回数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'プロモーションコード',
                'verbose_name_plural': 'プロモーションコード',
                'db_table': 'api_promocode',
            },
        ),
    ]
