# Generated by Django 5.2.9 on 2025-12-30 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_promocode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='メッセージ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='送信者')),
            ],
            options={
                'verbose_name': 'チャットメッセージ',
                'verbose_name_plural': 'チャットメッセージ',
                'db_table': 'api_chatmessage',
                'ordering': ['-created_at'],
            },
        ),
    ]
