# Generated by Django 5.2.9 on 2025-12-31 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, help_text='適用された割引額（円）', verbose_name='割引額'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='api.promocode', verbose_name='プロモーションコード'),
        ),
    ]
