# Generated by Django 5.2.9 on 2025-12-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reservation_discount_amount_reservation_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount_amount',
            field=models.PositiveIntegerField(help_text='円単位', verbose_name='割引額'),
        ),
    ]
