# Generated by Django 5.2.9 on 2025-12-31 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatmessage'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageRead',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chat_read_status', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('last_read_at', models.DateTimeField(help_text='この日時より前のメッセージは既読とみなす', verbose_name='最終既読日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'チャット既読状態',
                'verbose_name_plural': 'チャット既読状態',
                'db_table': 'api_chatmessageread',
            },
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(help_text='最大500文字', max_length=500, verbose_name='メッセージ内容'),
        ),
    ]
