# Generated by Django 5.2.9 on 2026-01-01 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatmessageread_alter_chatmessage_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emergency_stop', models.BooleanField(default=False, help_text='ONにするとチェックイン・チェックアウトが全て停止', verbose_name='緊急停止')),
                ('emergency_message', models.TextField(blank=True, default='', verbose_name='緊急停止時のメッセージ')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='ONにすると一般ユーザーはアクセス不可', verbose_name='メンテナンスモード')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'システム設定',
                'verbose_name_plural': 'システム設定',
                'db_table': 'api_systemsetting',
            },
        ),
    ]
