# Generated by Django 5.2.9 on 2026-01-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettransfer',
            name='intended_email',
            field=models.EmailField(blank=True, help_text='指定された場合、このメールのユーザーのみ受取可能', max_length=254, null=True, verbose_name='指定受取メール'),
        ),
    ]
