# Generated by Django 5.2.9 on 2026-01-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_intended_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='email_from_address',
            field=models.EmailField(default='noreply@example.com', max_length=254, verbose_name='送信元メールアドレス'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='email_from_name',
            field=models.CharField(default='MATSU チケットシステム', max_length=100, verbose_name='送信者名'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='email_mode',
            field=models.CharField(choices=[('test', 'テストモード（メール送信しない）'), ('production', '本番モード（SendGrid送信）')], default='test', max_length=20, verbose_name='メール送信モード'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='sendgrid_api_key',
            field=models.CharField(blank=True, default='', help_text='本番モード時に使用するSendGrid APIキー', max_length=200, verbose_name='SendGrid APIキー'),
        ),
    ]
