# Generated by GitHub Copilot on 2026-01-19

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_create_admin_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketShareLink",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(verbose_name="有効期限")),
                ("revoked_at", models.DateTimeField(blank=True, null=True, verbose_name="無効化日時")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ticket_share_links", to="auth.user", verbose_name="作成者")),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="share_links", to="api.ticket", verbose_name="チケット")),
            ],
            options={
                "db_table": "api_ticketsharelink",
                "ordering": ["-created_at"],
                "verbose_name": "チケット共有リンク",
                "verbose_name_plural": "チケット共有リンク",
            },
        ),
    ]
